FROM websphere-liberty:kernel
COPY server.xml /config/
RUN installUtility install --acceptLicense defaultServer
COPY mssql-jdbc-6.4.0.jre8.jar /opt/ibm/wlp/usr/shared/resources/
ADD HelloWorldEAR.ear /config/dropins/